gerbv: src/callbacks.c File Reference
callbacks.c File Reference
Detailed Description
Callback functions for the GUI widgets.
Definition in file callbacks.c.
Functions
gint callbacks_get_selected_row_index (void)
void callbacks_new_activate (GtkMenuItem *menuitem, gpointer user_data)
void callbacks_open_project_activate (GtkMenuItem *menuitem, gpointer user_data)
void callbacks_open_layer_activate (GtkMenuItem *menuitem, gpointer user_data)
void callbacks_analyze_active_gerbers_activate (GtkMenuItem *menuitem, gpointer user_data)
void callbacks_analyze_active_drill_activate (GtkMenuItem *menuitem, gpointer user_data)
void callbacks_quit_activate (GtkMenuItem *menuitem, gpointer user_data)
void callbacks_about_activate (GtkMenuItem *menuitem, gpointer user_data)
void callbacks_update_statusbar (void)
Variables
gerbv_screen_t screen
Function Documentation
void callbacks_about_activate (GtkMenuItem * menuitem, gpointer user_data)
The help -> about menu item was selected.
Show the about dialog.
Definition at line 1201 of file callbacks.c.
References screen.
void callbacks_analyze_active_drill_activate (GtkMenuItem * menuitem, gpointer user_data)
The analyze -> analyze drill file menu item was selected.
Complie statistics on all open drill layers and then display them.
Definition at line 870 of file callbacks.c.
References gerbv_drill_stats_t::comment, gerbv_drill_stats_t::detect, drill_list::drill_count, gerbv_drill_stats_t::drill_list, drill_list::drill_num, drill_list::drill_size, drill_list::drill_unit, gerbv_drill_stats_t::error_list, error_list::error_text, gerbv_project_t::file, gerbv_drill_stats_t::G00, gerbv_drill_stats_t::G01, gerbv_drill_stats_t::G02, gerbv_drill_stats_t::G03, gerbv_drill_stats_t::G04, gerbv_drill_stats_t::G05, gerbv_drill_stats_t::G90, gerbv_drill_stats_t::G91, gerbv_drill_stats_t::G93, gerbv_drill_stats_t::G_unknown, generate_drill_analysis(), GERBV_LAYERTYPE_DRILL, GERBV_MESSAGE_ERROR, GERBV_MESSAGE_FATAL, GERBV_MESSAGE_NOTE, GERBV_MESSAGE_WARNING, gerbv_fileinfo_t::image, gerbv_fileinfo_t::isVisible, error_list::layer, gerbv_drill_stats_t::layer_count, gerbv_image_t::layertype, gerbv_drill_stats_t::M00, gerbv_drill_stats_t::M01, gerbv_drill_stats_t::M18, gerbv_drill_stats_t::M25, gerbv_drill_stats_t::M30, gerbv_drill_stats_t::M31, gerbv_drill_stats_t::M45, gerbv_drill_stats_t::M47, gerbv_drill_stats_t::M48, gerbv_drill_stats_t::M71, gerbv_drill_stats_t::M72, gerbv_drill_stats_t::M95, gerbv_drill_stats_t::M97, gerbv_drill_stats_t::M98, gerbv_drill_stats_t::M_unknown, mainProject, gerbv_project_t::max_files, gerbv_fileinfo_t::name, drill_list::next, error_list::next, error_list::type, and gerbv_drill_stats_t::unknown.
void callbacks_analyze_active_gerbers_activate (GtkMenuItem * menuitem, gpointer user_data)
The analyze -> analyze Gerbers menu item was selected.
Complie statistics on all open Gerber layers and then display them.
Definition at line 473 of file callbacks.c.
References gerbv_stats_t::aperture_list, gerbv_stats_t::D1, gerbv_stats_t::D2, gerbv_stats_t::D3, gerbv_stats_t::D_code_list, gerbv_stats_t::D_error, gerbv_stats_t::D_unknown, gerbv_stats_t::error_list, error_list::error_text, gerbv_project_t::file, gerbv_stats_t::G0, gerbv_stats_t::G1, gerbv_stats_t::G10, gerbv_stats_t::G11, gerbv_stats_t::G12, gerbv_stats_t::G2, gerbv_stats_t::G3, gerbv_stats_t::G36, gerbv_stats_t::G37, gerbv_stats_t::G4, gerbv_stats_t::G54, gerbv_stats_t::G55, gerbv_stats_t::G70, gerbv_stats_t::G71, gerbv_stats_t::G74, gerbv_stats_t::G75, gerbv_stats_t::G90, gerbv_stats_t::G91, gerbv_stats_t::G_unknown, generate_gerber_analysis(), GERBV_LAYERTYPE_RS274X, GERBV_MESSAGE_ERROR, GERBV_MESSAGE_FATAL, GERBV_MESSAGE_NOTE, GERBV_MESSAGE_WARNING, gerbv_stats_t::I, gerbv_fileinfo_t::image, gerbv_fileinfo_t::isVisible, gerbv_stats_t::J, error_list::layer, gerbv_stats_t::layer_count, gerbv_image_t::layertype, gerbv_stats_t::M0, gerbv_stats_t::M1, gerbv_stats_t::M2, gerbv_stats_t::M_unknown, mainProject, gerbv_project_t::max_files, gerbv_fileinfo_t::name, error_list::next, gerbv_stats_t::star, error_list::type, gerbv_stats_t::unknown, gerbv_stats_t::X, and gerbv_stats_t::Y.
gint callbacks_get_selected_row_index (void)
This fcn returns the index of selected layer (selected in the layer window on left).
Definition at line 1621 of file callbacks.c.
References screen.
void callbacks_new_activate (GtkMenuItem * menuitem, gpointer user_data)
The file -> new menu item was selected.
Create new project.
Definition at line 131 of file callbacks.c.
References interface_get_alert_dialog_response(), gerbv_project_t::last_loaded, mainProject, and gerbv_project_t::project.
void callbacks_open_layer_activate (GtkMenuItem * menuitem, gpointer user_data)
The file -> open layer menu item was selected.
Open a layer (or layers) from a file.
Definition at line 212 of file callbacks.c.
References gerbv_open_layer_from_filename(), gerbv_render_zoom_to_fit_display(), mainProject, gerbv_project_t::path, and screen.
void callbacks_open_project_activate (GtkMenuItem * menuitem, gpointer user_data)
The file -> open menu item was selected.
Open a project file.
Definition at line 162 of file callbacks.c.
References gerbv_render_zoom_to_fit_display(), interface_get_alert_dialog_response(), gerbv_project_t::last_loaded, mainProject, gerbv_project_t::path, and screen.
void callbacks_quit_activate (GtkMenuItem * menuitem, gpointer user_data)
The file -> quit menu item was selected.
Check that all changes have been saved, and then quit.
Definition at line 1171 of file callbacks.c.
References gerbv_project_t::file, interface_get_alert_dialog_response(), gerbv_project_t::last_loaded, gerbv_fileinfo_t::layer_dirty, and mainProject.
void callbacks_update_statusbar (void)
Displays additional information in the statusbar.
The Statusbar is divided into three sections:
statusbar.coordstr for coords
statusbar.diststr for displaying measured distances or the designator (right click on a graphically marked and also actively selected part)
statusbar.msg for e.g. showing progress of actions
Definition at line 2654 of file callbacks.c.
References screen.
Variable Documentation
gerbv_screen_t screen
Global variable to keep track of what's happening on the screen.
Declared extern in gerbv_screen.h
Definition at line 158 of file main.c.
Referenced by callbacks_about_activate(), callbacks_get_selected_row_index(), callbacks_open_layer_activate(), callbacks_open_project_activate(), callbacks_update_statusbar(), render_calculate_zoom_from_outline(), and render_draw_measure_distance().