gerbv: src/callbacks.h File Reference
callbacks.h File Reference
Gerbv
Functions
void callbacks_new_activate (GtkMenuItem *menuitem, gpointer user_data)
void callbacks_open_project_activate (GtkMenuItem *menuitem, gpointer user_data)
void callbacks_open_layer_activate (GtkMenuItem *menuitem, gpointer user_data)
gboolean callbacks_quit_activate (GtkMenuItem *menuitem, gpointer user_data)
void callbacks_toggle_layer_visibility_activate (GtkMenuItem *menuitem, gpointer user_data)
void callbacks_analyze_active_gerbers_activate (GtkMenuItem *menuitem, gpointer user_data)
void callbacks_analyze_active_drill_activate (GtkMenuItem *menuitem, gpointer user_data)
void callbacks_about_activate (GtkMenuItem *menuitem, gpointer user_data)
void callbacks_bugs_activate (GtkMenuItem *menuitem, gpointer user_data)
void callbacks_update_statusbar (void)
Detailed Description
Header info for the GUI callback functions.
Definition in file callbacks.h.
Function Documentation
void callbacks_about_activate (GtkMenuItem * menuitem, gpointer user_data)
The help -> about menu item was selected.
Show the about dialog.
Definition at line 1491 of file callbacks.c.
References screen.
void callbacks_analyze_active_drill_activate (GtkMenuItem * menuitem, gpointer user_data)
The analyze -> analyze drill file menu item was selected.
Complie statistics on all open drill layers and then display them.
Definition at line 1152 of file callbacks.c.
References gerbv_project_t::file, generate_drill_analysis(), gerbv_drill_stats_destroy(), GERBV_LAYERTYPE_DRILL, gerbv_project_t::last_loaded, gerbv_image_t::layertype, and mainProject.
void callbacks_analyze_active_gerbers_activate (GtkMenuItem * menuitem, gpointer user_data)
The analyze -> analyze Gerbers menu item was selected.
Compile statistics on all open Gerber layers and then display them.
Definition at line 775 of file callbacks.c.
References gerbv_project_t::file, generate_gerber_analysis(), GERBV_LAYERTYPE_RS274X, gerbv_stats_destroy(), gerbv_project_t::last_loaded, gerbv_image_t::layertype, and mainProject.
void callbacks_bugs_activate (GtkMenuItem * menuitem, gpointer user_data)
The help -> bugs menu item was selected.
Show the known bugs window
Definition at line 1577 of file callbacks.c.
void callbacks_new_activate (GtkMenuItem * menuitem, gpointer user_data)
The file -> new menu item was selected.
Create new project.
Definition at line 156 of file callbacks.c.
References interface_get_alert_dialog_response(), gerbv_project_t::last_loaded, mainProject, and gerbv_project_t::project.
void callbacks_open_layer_activate (GtkMenuItem * menuitem, gpointer user_data)
The file -> open layer menu item was selected.
Open a layer (or layers) from a file.
Definition at line 253 of file callbacks.c.
References gerbv_open_layer_from_filename(), gerbv_render_zoom_to_fit_display(), mainProject, gerbv_project_t::path, and screen.
void callbacks_open_project_activate (GtkMenuItem * menuitem, gpointer user_data)
The file -> open menu item was selected.
Open a project file.
Definition at line 187 of file callbacks.c.
References gerbv_render_zoom_to_fit_display(), interface_get_alert_dialog_response(), gerbv_project_t::last_loaded, mainProject, gerbv_project_t::path, and screen.
gboolean callbacks_quit_activate (GtkMenuItem * menuitem, gpointer user_data)
The file -> quit menu item was selected or the user requested the main window to be closed by other means.
Check that all changes have been saved, and then quit.
Definition at line 1459 of file callbacks.c.
References gerbv_project_t::file, interface_get_alert_dialog_response(), gerbv_project_t::last_loaded, gerbv_fileinfo_t::layer_dirty, and mainProject.
void callbacks_toggle_layer_visibility_activate (GtkMenuItem * menuitem, gpointer user_data)
View/"Toggle visibility layer X" or Current layer/"Toggle visibility" menu item was activated.
Set the isVisible flag on file X and update the treeview and rendering.
Definition at line 685 of file callbacks.c.
References callbacks_get_selected_row_index(), gerbv_project_t::file, GERBV_RENDER_TYPE_GDK_XOR, gerbv_fileinfo_t::isVisible, gerbv_project_t::last_loaded, mainProject, gerbv_render_info_t::renderType, and screen.
void callbacks_update_statusbar (void)
Displays additional information in the statusbar.
The Statusbar is divided into three sections:
statusbar.coordstr for coords
statusbar.diststr for displaying measured distances or the designator (right click on a graphically marked and also actively selected part)
statusbar.msg for e.g. showing progress of actions
Definition at line 3249 of file callbacks.c.
References screen.