gerbv: src/exportimage.c File Reference
exportimage.c File Reference
Detailed Description
This file contains image exporting functions for exporting to PNG, PDF, SVG, and Postscript formats.
Definition in file exportimage.c.
Functions
void gerbv_export_png_file_from_project_autoscaled (gerbv_project_t *gerbvProject, int widthInPixels, int heightInPixels, gchar const *filename)
void gerbv_export_png_file_from_project (gerbv_project_t *gerbvProject, gerbv_render_info_t *renderInfo, gchar const *filename)
void gerbv_export_pdf_file_from_project_autoscaled (gerbv_project_t *gerbvProject, int widthInPoints, int heightInPoints, gchar const *filename)
void gerbv_export_pdf_file_from_project (gerbv_project_t *gerbvProject, gerbv_render_info_t *renderInfo, gchar const *filename)
void gerbv_export_postscript_file_from_project_autoscaled (gerbv_project_t *gerbvProject, int widthInPoints, int heightInPoints, gchar const *filename)
void gerbv_export_postscript_file_from_project (gerbv_project_t *gerbvProject, gerbv_render_info_t *renderInfo, gchar const *filename)
void gerbv_export_svg_file_from_project_autoscaled (gerbv_project_t *gerbvProject, int widthInPoints, int heightInPoints, gchar const *filename)
void gerbv_export_svg_file_from_project (gerbv_project_t *gerbvProject, gerbv_render_info_t *renderInfo, gchar const *filename)
Function Documentation
void gerbv_export_pdf_file_from_project (gerbv_project_t * gerbvProject, gerbv_render_info_t * renderInfo, gchar const * filename)
Render a project to a PDF file using user-specified render info.
Parameters:
gerbvProject the project to render
renderInfo the render settings for the rendered image
filename the filename for the exported PDF file
Definition at line 128 of file exportimage.c.
References gerbv_render_info_t::displayHeight, and gerbv_render_info_t::displayWidth.
Referenced by gerbv_export_pdf_file_from_project_autoscaled().
void gerbv_export_pdf_file_from_project_autoscaled (gerbv_project_t * gerbvProject, int widthInPoints, int heightInPoints, gchar const * filename)
Render a project to a PDF file, autoscaling the layers to fit inside the specified image dimensions.
Parameters:
gerbvProject the project to render
widthInPoints the width of the rendered picture (in pixels)
heightInPoints the height of the rendered picture (in pixels)
filename the filename for the exported PDF file
Definition at line 120 of file exportimage.c.
References gerbv_export_pdf_file_from_project(), and gerbv_render_zoom_to_fit_display().
void gerbv_export_png_file_from_project (gerbv_project_t * gerbvProject, gerbv_render_info_t * renderInfo, gchar const * filename)
Render a project to a PNG file using user-specified render info.
Parameters:
gerbvProject the project to render
renderInfo the render settings for the rendered image
filename the filename for the exported PNG file
Definition at line 87 of file exportimage.c.
References gerbv_render_info_t::displayHeight, and gerbv_render_info_t::displayWidth.
Referenced by gerbv_export_png_file_from_project_autoscaled().
void gerbv_export_png_file_from_project_autoscaled (gerbv_project_t * gerbvProject, int widthInPixels, int heightInPixels, gchar const * filename)
Render a project to a PNG file, autoscaling the layers to fit inside the specified image dimensions.
Parameters:
gerbvProject the project to render
widthInPixels the width of the rendered picture (in pixels)
heightInPixels the height of the rendered picture (in pixels)
filename the filename for the exported PNG file
Examples:
example3.c.
Definition at line 74 of file exportimage.c.
References gerbv_export_png_file_from_project(), and gerbv_render_zoom_to_fit_display().
void gerbv_export_postscript_file_from_project (gerbv_project_t * gerbvProject, gerbv_render_info_t * renderInfo, gchar const * filename)
Render a project to a Postscript file using user-specified render info.
Parameters:
gerbvProject the project to render
renderInfo the render settings for the rendered image
filename the filename for the exported Postscript file
Definition at line 146 of file exportimage.c.
References gerbv_render_info_t::displayHeight, and gerbv_render_info_t::displayWidth.
Referenced by gerbv_export_postscript_file_from_project_autoscaled().
void gerbv_export_postscript_file_from_project_autoscaled (gerbv_project_t * gerbvProject, int widthInPoints, int heightInPoints, gchar const * filename)
Render a project to a Postscript file, autoscaling the layers to fit inside the specified image dimensions.
Parameters:
gerbvProject the project to render
widthInPoints the width of the rendered picture (in pixels)
heightInPoints the height of the rendered picture (in pixels)
filename the filename for the exported Postscript file
Definition at line 138 of file exportimage.c.
References gerbv_export_postscript_file_from_project(), and gerbv_render_zoom_to_fit_display().
void gerbv_export_svg_file_from_project (gerbv_project_t * gerbvProject, gerbv_render_info_t * renderInfo, gchar const * filename)
Render a project to a file using user-specified render info.
Parameters:
gerbvProject the project to render
renderInfo the render settings for the rendered image
filename the filename for the exported file
Definition at line 163 of file exportimage.c.
References gerbv_render_info_t::displayHeight, and gerbv_render_info_t::displayWidth.
Referenced by gerbv_export_svg_file_from_project_autoscaled().
void gerbv_export_svg_file_from_project_autoscaled (gerbv_project_t * gerbvProject, int widthInPoints, int heightInPoints, gchar const * filename)
Render a project to a SVG file, autoscaling the layers to fit inside the specified image dimensions.
Parameters:
gerbvProject the project to render
widthInPoints the width of the rendered picture (in pixels)
heightInPoints the height of the rendered picture (in pixels)
filename the filename for the exported file
Definition at line 155 of file exportimage.c.
References gerbv_export_svg_file_from_project(), and gerbv_render_zoom_to_fit_display().