gerbv: src/gerb_stats.c File Reference
gerb_stats.c File Reference
Detailed Description
Statistics generating functions for RS274X files.
Definition in file gerb_stats.c.
Functions
gerbv_stats_t * gerbv_stats_new (void)
void gerbv_stats_add_layer (gerbv_stats_t *accum_stats, gerbv_stats_t *input_stats, int this_layer)
Function Documentation
void gerbv_stats_add_layer (gerbv_stats_t * accum_stats, gerbv_stats_t * input_stats, int this_layer)
This fcn is called with a two gerbv_stats_t structs: accum_stats and input_stats. Accum_stats holds a list of stats accumulated for all layers. This will be reported in the report window. Input_stats holds a list of the stats for one particular layer to be added to the accumulated list.
Definition at line 94 of file gerb_stats.c.
References gerbv_stats_t::aperture_list, gerbv_stats_t::D1, gerbv_stats_t::D2, gerbv_stats_t::D3, gerbv_stats_t::D_code_list, gerbv_stats_t::D_error, gerbv_stats_t::D_unknown, gerbv_stats_t::error_list, error_list::error_text, gerbv_stats_t::G0, gerbv_stats_t::G1, gerbv_stats_t::G10, gerbv_stats_t::G11, gerbv_stats_t::G12, gerbv_stats_t::G2, gerbv_stats_t::G3, gerbv_stats_t::G36, gerbv_stats_t::G37, gerbv_stats_t::G4, gerbv_stats_t::G54, gerbv_stats_t::G55, gerbv_stats_t::G70, gerbv_stats_t::G71, gerbv_stats_t::G74, gerbv_stats_t::G75, gerbv_stats_t::G90, gerbv_stats_t::G91, gerbv_stats_t::G_unknown, gerbv_stats_t::I, gerbv_stats_t::J, gerbv_stats_t::layer_count, gerbv_stats_t::M0, gerbv_stats_t::M1, gerbv_stats_t::M2, gerbv_stats_t::M_unknown, error_list::next, gerbv_stats_t::star, error_list::type, gerbv_stats_t::unknown, gerbv_stats_t::X, and gerbv_stats_t::Y.
Referenced by generate_gerber_analysis().
gerbv_stats_t* gerbv_stats_new (void)
Allocates a new gerbv_stats structure.
Returns:
gerbv_stats pointer on success, NULL on ERROR
Definition at line 49 of file gerb_stats.c.
Referenced by generate_gerber_analysis(), and parse_gerb().