gerbv: src/interface.c File Reference
interface.c File Reference
Detailed Description
GUI building functions for Gerbv.
Definition in file interface.c.
Functions
gboolean interface_get_alert_dialog_response (gchar *primaryText, gchar *secondaryText, gboolean show_checkbox, gboolean *ask_to_show_again)
void interface_show_alert_dialog (gchar *primaryText, gchar *secondaryText, gboolean show_checkbox, gboolean *ask_to_show_again)
Function Documentation
gboolean interface_get_alert_dialog_response (gchar * primaryText, gchar * secondaryText, gboolean show_checkbox, gboolean * ask_to_show_again)
This dialog box shows a message and two buttons: "OK" and "Cancel".
It returns gboolean 1 if the user clicked "OK", and gboolean 0 if the user clicked "Cancel".
Definition at line 1283 of file interface.c.
Referenced by callbacks_new_activate(), callbacks_open_project_activate(), and callbacks_quit_activate().
void interface_show_alert_dialog (gchar * primaryText, gchar * secondaryText, gboolean show_checkbox, gboolean * ask_to_show_again)
This dialog box shows a textmessage and one buttons: "OK".
It does not return anything.
Definition at line 1379 of file interface.c.