gerbv: src/pick-and-place.c File Reference
pick-and-place.c File Reference
Detailed Description
PNP (pick-and-place) parsing functions.
Definition in file pick-and-place.c.
Functions
void gerb_transf_rotate (gerbv_transf_t *transf, double angle)
void gerb_transf_shift (gerbv_transf_t *transf, double shift_x, double shift_y)
static double pick_and_place_get_float_unit (char *str)
int pick_and_place_screen_for_delimiter (char *str, int n)
GArray * pick_and_place_parse_file (gerb_file_t *fd)
Function Documentation
void gerb_transf_rotate (gerbv_transf_t * transf, double angle)
Rotation.
append rotation to transformation.
Parameters:
transf transformation to be modified
angle in rad (counterclockwise rotation)
Definition at line 115 of file pick-and-place.c.
Referenced by pick_and_place_parse_file().
void gerb_transf_shift (gerbv_transf_t * transf, double shift_x, double shift_y)
Translation.
append translation to transformation.
Parameters:
transf transformation to be modified
shift_x translation in x direction
shift_y translation in y direction
Definition at line 135 of file pick-and-place.c.
static double pick_and_place_get_float_unit (char * str) [static]
Parses a string representing float number with a unit, default is mil.
Definition at line 158 of file pick-and-place.c.
Referenced by pick_and_place_parse_file().
GArray* pick_and_place_parse_file (gerb_file_t * fd)
Parses the PNP data.
two lists are filled with the row data.
One for the scrollable list in the search and select parts interface, the other one a mere two columned list, which drives the autocompletion when entering a search.
It also tries to determine the shape of a part and sets pnp_state->shape accordingly which will be used when drawing the selections as an overlay on screen.
Returns:
the initial node of the pnp_state netlist
Definition at line 227 of file pick-and-place.c.
References gerb_transf_rotate(), and pick_and_place_get_float_unit().
int pick_and_place_screen_for_delimiter (char * str, int n)
search a string for a delimiter.
Must occur at least n times.
Definition at line 180 of file pick-and-place.c.