gerbv: src/render.h File Reference
render.h File Reference
libgerbv
Functions
gerbv_stats_t * generate_gerber_analysis (void)
gerbv_drill_stats_t * generate_drill_analysis (void)
void render_calculate_zoom_from_outline (GtkWidget *widget, GdkEventButton *event)
void render_toggle_measure_line (void)
void render_draw_measure_distance (void)
Detailed Description
Header info for the rendering support functions for libgerbv.
Definition in file render.h.
Function Documentation
gerbv_drill_stats_t* generate_drill_analysis (void)
This fills out the project's Drill statistics table. It is called from within callbacks.c when the user asks for a Drill report.
Definition at line 694 of file render.c.
References gerbv_image_t::drill_stats, gerbv_project_t::file, gerbv_drill_stats_add_layer(), gerbv_drill_stats_new(), GERBV_LAYERTYPE_DRILL, gerbv_fileinfo_t::image, gerbv_fileinfo_t::isVisible, gerbv_project_t::last_loaded, gerbv_image_t::layertype, and mainProject.
Referenced by callbacks_analyze_active_drill_activate().
gerbv_stats_t* generate_gerber_analysis (void)
This fills out the project's Gerber statistics table. It is called from within callbacks.c when the user asks for a Gerber report.
Definition at line 667 of file render.c.
References gerbv_project_t::file, GERBV_LAYERTYPE_RS274X, gerbv_image_t::gerbv_stats, gerbv_stats_add_layer(), gerbv_stats_new(), gerbv_fileinfo_t::image, gerbv_fileinfo_t::isVisible, gerbv_project_t::last_loaded, gerbv_image_t::layertype, and mainProject.
Referenced by callbacks_analyze_active_gerbers_activate().
void render_calculate_zoom_from_outline (GtkWidget * widget, GdkEventButton * event)
Will determine the outline of the zoomed regions.
In case region to be zoomed is too small (which correspondes e.g. to a double click) it is interpreted as a right-click and will be used to identify a part from the CURRENT selection, which is drawn on screen
Definition at line 176 of file render.c.
References gerbv_render_info_t::displayHeight, gerbv_render_info_t::displayWidth, gerbv_render_info_t::lowerLeftX, gerbv_render_info_t::lowerLeftY, gerbv_render_info_t::scaleFactorX, gerbv_render_info_t::scaleFactorY, and screen.
void render_draw_measure_distance (void)
Displays a measured distance graphically on screen and in statusbar.
Definition at line 386 of file render.c.
References render_toggle_measure_line(), and screen.