gerbv: src/render.c File Reference
render.c File Reference
Detailed Description
Rendering support functions for libgerbv.
Definition in file render.c.
Functions
void render_calculate_zoom_from_outline (GtkWidget *widget, GdkEventButton *event)
void render_draw_measure_distance (void)
gerbv_stats_t * generate_gerber_analysis (void)
gerbv_drill_stats_t * generate_drill_analysis (void)
Variables
gerbv_screen_t screen
Function Documentation
gerbv_drill_stats_t* generate_drill_analysis (void)
This fills out the project's Drill statistics table. It is called from within callbacks.c when the user asks for a Drill report.
Definition at line 601 of file render.c.
References gerbv_image_t::drill_stats, gerbv_project_t::file, gerbv_drill_stats_add_layer(), gerbv_drill_stats_new(), GERBV_LAYERTYPE_DRILL, gerbv_fileinfo_t::image, gerbv_fileinfo_t::isVisible, gerbv_image_t::layertype, mainProject, and gerbv_project_t::max_files.
Referenced by callbacks_analyze_active_drill_activate().
gerbv_stats_t* generate_gerber_analysis (void)
This fills out the project's Gerber statistics table. It is called from within callbacks.c when the user asks for a Gerber report.
Definition at line 574 of file render.c.
References gerbv_project_t::file, GERBV_LAYERTYPE_RS274X, gerbv_image_t::gerbv_stats, gerbv_stats_add_layer(), gerbv_stats_new(), gerbv_fileinfo_t::image, gerbv_fileinfo_t::isVisible, gerbv_image_t::layertype, mainProject, and gerbv_project_t::max_files.
Referenced by callbacks_analyze_active_gerbers_activate().
void render_calculate_zoom_from_outline (GtkWidget * widget, GdkEventButton * event)
Will determine the outline of the zoomed regions.
In case region to be zoomed is too small (which correspondes e.g. to a double click) it is interpreted as a right-click and will be used to identify a part from the CURRENT selection, which is drawn on screen
Definition at line 166 of file render.c.
References gerbv_render_info_t::displayHeight, gerbv_render_info_t::displayWidth, gerbv_render_info_t::lowerLeftX, gerbv_render_info_t::lowerLeftY, gerbv_render_info_t::scaleFactorX, gerbv_render_info_t::scaleFactorY, and screen.
void render_draw_measure_distance (void)
Displays a measured distance graphically on screen and in statusbar.
activated when using SHIFT and mouse dragged to measure distances
under win32 graphical annotations are currently disabled (GTK 2.47)
Definition at line 299 of file render.c.
References gerbv_render_info_t::scaleFactorX, gerbv_render_info_t::scaleFactorY, and screen.
Variable Documentation
gerbv_screen_t screen
Global variable to keep track of what's happening on the screen.
Declared extern in gerbv_screen.h
Definition at line 158 of file main.c.